### PR TITLE
Fix developer setup of Parsoid after changes in MediaWiki

### LINKED ISSUE #544: Fatal error: Uncaught Error: Cannot access private property AutoLoader::$psr4Namespaces
```
Fatal error:  Uncaught Error: Cannot access private property AutoLoader::$psr4Namespaces in /srv/patchdemo-wikis/b4db406cc4/w/settings.d/services-parsoid.php:7
Stack trace:
#0 /srv/patchdemo-wikis/b4db406cc4/w/LocalSettings.php(216): include_once()
#1 /srv/patchdemo-wikis/b4db406cc4/w/includes/Setup.php(209): require_once('/srv/patchdemo-...')
#2 /srv/patchdemo-wikis/b4db406cc4/w/includes/WebStart.php(92): require_once('/srv/patchdemo-...')
#3 /srv/patchdemo-wikis/b4db406cc4/w/index.php(44): require('/srv/patchdemo-...')
#4 {main}
  thrown in /srv/patchdemo-wikis/b4db406cc4/w/settings.d/services-parsoid.php on line 7
```

### PR DESCRIPTION
**Pull request by MatmaRex**
Fixes #544

### CODE REVIEW

File: localsettings/services-parsoid.php [hunk 1]
```diff
@@ -4,9 +4,16 @@
 $wgEnableRestAPI = true;
 if ( file_exists( 'parsoid/extension.json' ) ) {
 	// Ensure we load the right Parsoid (not via Composer)
-	AutoLoader::$psr4Namespaces += [
-		'Wikimedia\\Parsoid\\' => 'parsoid/src',
-	];
+	if ( method_exists( AutoLoader::class, 'registerNamespaces' ) ) {
```
Comment (jdforrester) [inline localsettings/services-parsoid.php:7]: This has existed since https://gerrit.wikimedia.org/r/c/mediawiki/core/+/773229 in REL1_39; are you trying to support REL1_38/REL1_35 still here? Might be worth a comment explaining when this can be dropped.
