### PR TITLE
Store wiki cache in structured DB instead of flat file

### LINKED ISSUE #113: wikicache.json can cache partially built wiki results
If someone visits index.php while a wiki is building, the metadata for a partially built wiki may get cached. We could not cache broken wikis, but that would mean we try to evaluate metadata for actually broken wikis on every view.

### PR DESCRIPTION
**Pull request by edg2s**
Fixes #113, #207

### CODE REVIEW

**Comment by MatmaRex** [comment]
I agree that this seems like a good thing to do, this has gotten too complicated to keep it in flat text files :(

Maybe there's a good reason for this in the code (which I haven't read yet), but why SQLite? We already have MySQL, you'd just need to `CREATE DATABASE` in setup.sh or something. `CREATE TABLE` and migrations should go in setup.sh either way.

**Comment by edg2s** [comment]
Good point, I was thinking of the wiki dbs as separate but we already talk to them directly in a few places.

**Comment by edg2s** [comment]
Fixed

File: sql/patchdemo.sql [hunk 1]
```diff
@@ -0,0 +1,28 @@
+CREATE DATABASE IF NOT EXISTS patchdemo COLLATE "utf8_general_ci";
```
Comment (MatmaRex) [inline sql/patchdemo.sql:1]: Why `COLLATE "utf8_general_ci"`? I would just remove this part and use the default.

I might be out of date on this, but IIRC in MySQL, `utf8mb4` is the real Unicode, while `utf8` is BMP-only Unicode and it will explode in your face when you try to use non-BMP characters like emojis. Not sure how exactly a collation might explode, but still.

It seems that the default is `utf8mb4_0900_ai_ci` (https://dev.mysql.com/doc/refman/8.0/en/charset-applications.html), no idea what exactly it does, but it sounds reassuring.

Comment (edg2s) [reply sql/patchdemo.sql:1]: Sure - I'm just copying from old stuff, but if the defaults are sensible that's fine.

Comment (edg2s) [reply sql/patchdemo.sql]: Fixed

File: setup.sh [hunk 2]
```diff
@@ -17,11 +17,11 @@ sudo -u www-data mkdir composer
 # Create folder for wikis
 sudo -u www-data mkdir wikis
 
-# create a database user that is allowed to create databases for each wiki
-sudo mysql -u root --password='' -e "
-CREATE USER 'patchdemo'@'localhost' IDENTIFIED BY 'patchdemo';
-GRANT ALL PRIVILEGES ON \`patchdemo\_%\`.* TO 'patchdemo'@'localhost';
-"
+# Create a database user that is allowed to create databases for each wiki,
+# and the central patchdemo database
```
Comment (MatmaRex) [inline setup.sh:21]: Duplicate comment (line 23)

File: includes.php [hunk 3]
```diff
@@ -66,6 +66,191 @@
...
+	die( $mysqli->connect_error );
+}
+
+function insert_wiki_data( string $wiki, string $creator, int $created, array $patches = [] ) {
+	global $mysqli;
+	$stmt = $mysqli->prepare( '
+		INSERT INTO wikis
+		(wiki, creator, created, patches)
+		VALUES(?, ?, NOW(), ?)
+		ON DUPLICATE KEY UPDATE
```
Comment (MatmaRex) [inline includes.php:80]: I don't like this but I think I'll propose my own change. (This looks like a good way to lose lots of data and in particular to reset the `created` date accidentally; but it looks like it needs a few changes elsewhere.)

Comment (MatmaRex) [reply includes.php:80]: I see now that it only updates `patches`? (next line)

I missed it at first so that must mean it's very confusing. I still don't like it. :)

File: includes.php [hunk 4]
```diff
@@ -66,6 +66,191 @@
...
+	$data['announcedTasks'] = json_decode( $data['announcedTasks'] ) ?: [];
+
+	// Populate patch list
+	$patchList = [];
+	$linkedTasks = [];
+	if ( $data['patches'] ) {
+		foreach ( $data['patches'] as $patch ) {
+			[ $r, $p ] = explode( ',', $patch );
+			$patchData = get_patch_data( $r, $p );
+			$patchList[$patch] = get_patch_data( $r, $p );
```
Comment (MatmaRex) [inline includes.php:132]: Calling `get_patch_data()` twice will do SQL and Gerrit API queries twice?

File: includes.php [hunk 5]
```diff
@@ -66,6 +66,191 @@
 		</header>
 		<main>';
 
+$mysqli = new mysqli( 'localhost', 'patchdemo', 'patchdemo', 'patchdemo' );
+if ( $mysqli->connect_error ) {
+	die( $mysqli->connect_error );
+}
+
+function insert_wiki_data( string $wiki, string $creator, int $created, array $patches = [] ) {
```
Comment (MatmaRex) [inline includes.php:74]: `$created` is never used, which presumably causes the dates to be lost in the `migrateToSql.php` script.

File: sql/patchdemo.sql [hunk 6]
```diff
@@ -0,0 +1,28 @@
+CREATE DATABASE IF NOT EXISTS patchdemo;
+
+USE patchdemo;
+
+CREATE TABLE IF NOT EXISTS wikis (
```
Comment (MatmaRex) [inline sql/patchdemo.sql:5]: We do queries with `ORDER BY created`, so there should be an index on it?

Comment (edg2s) [reply sql/patchdemo.sql:5]: If you want... but for 100 rows and index won't make much difference

**Comment by MatmaRex** [comment]
So, how would I deploy this on patchdemo.wmflabs.org?

# Checkout this commit
# Run setup.sh to create database
# Run migrateToSql.php
# Carefully compare the outputs of index.php, and create some wikis

If something is broken, I just checkout master again, and it should be happy. Might need to drop the database manually, which should be fine too.

File: includes.php (hunk 5 above)
Comment (edg2s) [reply includes.php:74]: Fixed

File: includes.php (hunk 3 above)
Comment (edg2s) [reply includes.php:80]: Yeah - we should use some database abstraction framework probably. Writing queries gets out of hand fast.

File: includes.php (hunk 4 above)
Comment (edg2s) [reply includes.php:132]: Looks like a typo. Fixed.

File: setup.sh (hunk 2 above)
Comment (edg2s) [reply setup.sh:21]: not quite - this says the user is allowed to create the central patchdemo database

the subsequent comment is actually creating it

I guess the comma is a bit ambiguous.

**Comment by edg2s** [comment]
> If something is broken, I just checkout master again, and it should be happy. Might need to drop the database manually, which should be fine too.

Sounds about right. You should be able to revert at any point, although going forward we stop creating the metadata flat files (e.g. creator.txt)

File: sql/user.sql [hunk 7]
```diff
@@ -0,0 +1,3 @@
+CREATE USER 'patchdemo'@'localhost' IDENTIFIED BY 'patchdemo';
+GRANT ALL PRIVILEGES ON `patchdemo%`.* TO 'patchdemo'@'localhost';
```
[the remark this answers is not in the document]
Comment (edg2s) [reply sql/user.sql:2]: Actually, I can add an IF NOT EXISTS to the CREATE USER

**Comment by MatmaRex** [comment]
I deployed it, everything looks good!

**Comment by MatmaRex** [comment]
Also, it looks like this kind of fixes #81 – duplicate patches are no longer shown in the table, because they can't be stored in the `patches` table (`patch` is a primary key).
